// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TodoApi.Data;

#nullable disable

namespace TodoApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506094104_addedAchievementDimonds")]
    partial class addedAchievementDimonds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("TodoApi")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("TodoApi.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<int>("RequirementValue")
                        .HasColumnType("integer")
                        .HasColumnName("requirementValue");

                    b.Property<int>("RewardAchievementPoints")
                        .HasColumnType("integer")
                        .HasColumnName("rewardAchievementPoints");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("achievements", "TodoApi");
                });

            modelBuilder.Entity("TodoApi.Models.DynamicTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isCompleted");

                    b.Property<DateTime?>("LastCompletedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastCompletedDate");

                    b.Property<DateTime?>("LastShownDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastShownDate");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<string>("RepeatDays")
                        .HasColumnType("text")
                        .HasColumnName("repeatDays");

                    b.Property<int?>("TimeBonusMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("timeBonusMinutes");

                    b.Property<TimeSpan?>("TimeOfDay")
                        .HasColumnType("interval")
                        .HasColumnName("timeOfDay");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("dynamicTasks", "TodoApi");
                });

            modelBuilder.Entity("TodoApi.Models.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("familyName");

                    b.HasKey("Id");

                    b.ToTable("families", "TodoApi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FamilyName = "Bang"
                        });
                });

            modelBuilder.Entity("TodoApi.Models.PushSubscriptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("p256dh");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("pushSubscriptions", "TodoApi");
                });

            modelBuilder.Entity("TodoApi.Models.SavingsGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdAt");

                    b.Property<bool>("IsReached")
                        .HasColumnType("boolean")
                        .HasColumnName("isReached");

                    b.Property<int>("TargetPoints")
                        .HasColumnType("integer")
                        .HasColumnName("targetPoints");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("savingsGoals", "TodoApi");
                });

            modelBuilder.Entity("TodoApi.Models.StaticTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isCompleted");

                    b.Property<bool>("IsRepeatable")
                        .HasColumnType("boolean")
                        .HasColumnName("isRepeatable");

                    b.Property<DateTime?>("LastCompletedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastCompletedDate");

                    b.Property<DateTime?>("LastShownDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastShownDate");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<string>("RepeatDays")
                        .HasColumnType("text")
                        .HasColumnName("repeatDays");

                    b.Property<int?>("TimeBonusMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("timeBonusMinutes");

                    b.Property<TimeSpan?>("TimeOfDay")
                        .HasColumnType("interval")
                        .HasColumnName("timeOfDay");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("staticTasks", "TodoApi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCompleted = false,
                            IsRepeatable = false,
                            Points = 2,
                            TimeBonusMinutes = 15,
                            Title = "Tømme opvaskemaskine & flyde den igen"
                        },
                        new
                        {
                            Id = 2,
                            IsCompleted = false,
                            IsRepeatable = false,
                            Points = 2,
                            TimeBonusMinutes = 15,
                            Title = "Tørre støv af"
                        },
                        new
                        {
                            Id = 3,
                            IsCompleted = false,
                            IsRepeatable = false,
                            Points = 2,
                            TimeBonusMinutes = 15,
                            Title = "Dække bord + tørre bord af"
                        },
                        new
                        {
                            Id = 4,
                            IsCompleted = false,
                            IsRepeatable = false,
                            Points = 2,
                            TimeBonusMinutes = 15,
                            Title = "Støvsuge hele huset"
                        },
                        new
                        {
                            Id = 5,
                            IsCompleted = false,
                            IsRepeatable = false,
                            Points = 2,
                            TimeBonusMinutes = 15,
                            Title = "Vaske gulv"
                        },
                        new
                        {
                            Id = 6,
                            IsCompleted = false,
                            IsRepeatable = false,
                            Points = 2,
                            TimeBonusMinutes = 15,
                            Title = "Hænge vasketøj op med en voksen"
                        },
                        new
                        {
                            Id = 7,
                            IsCompleted = false,
                            IsRepeatable = false,
                            Points = 2,
                            TimeBonusMinutes = 15,
                            Title = "Skylle af efter aftensmaden"
                        },
                        new
                        {
                            Id = 8,
                            IsCompleted = false,
                            IsRepeatable = false,
                            Points = 2,
                            TimeBonusMinutes = 15,
                            Title = "Pille tøj ned af tørrestativet"
                        },
                        new
                        {
                            Id = 9,
                            IsCompleted = false,
                            IsRepeatable = false,
                            Points = 2,
                            TimeBonusMinutes = 15,
                            Title = "Lægge tøj sammen + lægge tøj på plads med en voksen"
                        },
                        new
                        {
                            Id = 10,
                            IsCompleted = false,
                            IsRepeatable = false,
                            Points = 2,
                            TimeBonusMinutes = 15,
                            Title = "Tømme skraldespande"
                        },
                        new
                        {
                            Id = 11,
                            IsCompleted = false,
                            IsRepeatable = false,
                            Points = 2,
                            TimeBonusMinutes = 15,
                            Title = "Ordne badeværelser med en voksen"
                        },
                        new
                        {
                            Id = 12,
                            IsCompleted = false,
                            IsRepeatable = false,
                            Points = 2,
                            TimeBonusMinutes = 15,
                            Title = "Slå græs"
                        },
                        new
                        {
                            Id = 13,
                            IsCompleted = false,
                            IsRepeatable = false,
                            Points = 2,
                            TimeBonusMinutes = 15,
                            Title = "Fejrne ukrudt (min. 1 spand)"
                        },
                        new
                        {
                            Id = 14,
                            IsCompleted = false,
                            IsRepeatable = false,
                            Points = 2,
                            TimeBonusMinutes = 15,
                            Title = "Være med til at lave aftensmad"
                        },
                        new
                        {
                            Id = 15,
                            IsCompleted = false,
                            IsRepeatable = false,
                            Points = 2,
                            TimeBonusMinutes = 15,
                            Title = "Fylde op i køleskab med sodavand"
                        },
                        new
                        {
                            Id = 16,
                            IsCompleted = false,
                            IsRepeatable = false,
                            Points = 2,
                            TimeBonusMinutes = 15,
                            Title = "Give kattene mad"
                        },
                        new
                        {
                            Id = 17,
                            IsCompleted = false,
                            IsRepeatable = false,
                            Points = 2,
                            TimeBonusMinutes = 15,
                            Title = "Rede senge (Alle)"
                        });
                });

            modelBuilder.Entity("TodoApi.Models.TaskLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("DailyGoal")
                        .HasColumnType("integer")
                        .HasColumnName("dailyGoal");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("integer")
                        .HasColumnName("pointsEarned");

                    b.Property<int>("TasksCompleted")
                        .HasColumnType("integer")
                        .HasColumnName("tasksCompleted");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("taskLogs", "TodoApi");
                });

            modelBuilder.Entity("TodoApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementPoints")
                        .HasColumnType("integer")
                        .HasColumnName("achievementPoints");

                    b.Property<int>("BonusMinutesEarnedToday")
                        .HasColumnType("integer")
                        .HasColumnName("bonusMinutesEarnedToday");

                    b.Property<double>("CurrentMultiplier")
                        .HasColumnType("double precision")
                        .HasColumnName("currentMultiplier");

                    b.Property<int>("DailyGoal")
                        .HasColumnType("integer")
                        .HasColumnName("dailyGoal");

                    b.Property<int>("Emeralds")
                        .HasColumnType("integer")
                        .HasColumnName("emeralds");

                    b.Property<int?>("FamilyId")
                        .HasColumnType("integer")
                        .HasColumnName("familyId");

                    b.Property<string>("FamilyName")
                        .HasColumnType("text")
                        .HasColumnName("familyName");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean")
                        .HasColumnName("isPaused");

                    b.Property<bool>("IsTimerRunning")
                        .HasColumnType("boolean")
                        .HasColumnName("isTimerRunning");

                    b.Property<DateTime>("LastTimerUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastTimerUpdate");

                    b.Property<int>("MinutesLeftToday")
                        .HasColumnType("integer")
                        .HasColumnName("minutesLeftToday");

                    b.Property<DateTime?>("MultiplierExpiry")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("multiplierExpiry");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordHash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<int>("SaturdayBonusPot")
                        .HasColumnType("integer")
                        .HasColumnName("saturdayBonusPot");

                    b.Property<decimal>("SavingsBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("savingsBalance");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer")
                        .HasColumnName("totalPoints");

                    b.Property<int>("TotalTasksCompleted")
                        .HasColumnType("integer")
                        .HasColumnName("totalTasksCompleted");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("users", "TodoApi");
                });

            modelBuilder.Entity("TodoApi.Models.UserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("integer")
                        .HasColumnName("achievementId");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("unlockedAt");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.ToTable("userAchievements", "TodoApi");
                });

            modelBuilder.Entity("TodoApi.Models.DynamicTask", b =>
                {
                    b.HasOne("TodoApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TodoApi.Models.PushSubscriptionEntity", b =>
                {
                    b.HasOne("TodoApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TodoApi.Models.SavingsGoal", b =>
                {
                    b.HasOne("TodoApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TodoApi.Models.StaticTask", b =>
                {
                    b.HasOne("TodoApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("TodoApi.Models.TaskLog", b =>
                {
                    b.HasOne("TodoApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TodoApi.Models.User", b =>
                {
                    b.HasOne("TodoApi.Models.Family", null)
                        .WithMany("Users")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("TodoApi.Models.UserAchievement", b =>
                {
                    b.HasOne("TodoApi.Models.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");
                });

            modelBuilder.Entity("TodoApi.Models.Family", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
