// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TodoApi.Data;

#nullable disable

namespace TodoApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ToDoAPI.Models.DynamicTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastCompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastShownDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RepeatDays")
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("TimeOfDay")
                        .HasColumnType("interval");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DynamicTasks");
                });

            modelBuilder.Entity("ToDoAPI.Models.StaticTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastCompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastShownDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RepeatDays")
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("TimeOfDay")
                        .HasColumnType("interval");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StaticTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCompleted = false,
                            RepeatDays = "[]",
                            Title = "Tømme opvaskemaskine & flyde den igen"
                        },
                        new
                        {
                            Id = 2,
                            IsCompleted = false,
                            RepeatDays = "[]",
                            Title = "Tørre støv af"
                        },
                        new
                        {
                            Id = 3,
                            IsCompleted = false,
                            RepeatDays = "[]",
                            Title = "Dække bord + tørre bord af"
                        },
                        new
                        {
                            Id = 4,
                            IsCompleted = false,
                            RepeatDays = "[]",
                            Title = "Støvsuge hele huset"
                        },
                        new
                        {
                            Id = 5,
                            IsCompleted = false,
                            RepeatDays = "[]",
                            Title = "Vaske gulv"
                        },
                        new
                        {
                            Id = 6,
                            IsCompleted = false,
                            RepeatDays = "[]",
                            Title = "Hænge vasketøj op med en voksen"
                        },
                        new
                        {
                            Id = 7,
                            IsCompleted = false,
                            RepeatDays = "[]",
                            Title = "Skylle af efter aftensmaden"
                        },
                        new
                        {
                            Id = 8,
                            IsCompleted = false,
                            RepeatDays = "[]",
                            Title = "Pille tøj ned af tørrestativet"
                        },
                        new
                        {
                            Id = 9,
                            IsCompleted = false,
                            RepeatDays = "[]",
                            Title = "Lægge tøj sammen + lægge tøj på plads med en voksen"
                        },
                        new
                        {
                            Id = 10,
                            IsCompleted = false,
                            RepeatDays = "[]",
                            Title = "Tømme skraldespande"
                        },
                        new
                        {
                            Id = 11,
                            IsCompleted = false,
                            RepeatDays = "[]",
                            Title = "Ordne badeværelser med en voksen"
                        },
                        new
                        {
                            Id = 12,
                            IsCompleted = false,
                            RepeatDays = "[]",
                            Title = "Slå græs"
                        },
                        new
                        {
                            Id = 13,
                            IsCompleted = false,
                            RepeatDays = "[]",
                            Title = "Fejrne ukrudt (min. 1 spand)"
                        },
                        new
                        {
                            Id = 14,
                            IsCompleted = false,
                            RepeatDays = "[]",
                            Title = "Være med til at lave aftensmad"
                        },
                        new
                        {
                            Id = 15,
                            IsCompleted = false,
                            RepeatDays = "[]",
                            Title = "Fylde op i køleskab med sodavand"
                        },
                        new
                        {
                            Id = 16,
                            IsCompleted = false,
                            RepeatDays = "[]",
                            Title = "Give kattene mad"
                        },
                        new
                        {
                            Id = 17,
                            IsCompleted = false,
                            RepeatDays = "[]",
                            Title = "Rede senge (Alle)"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
